[project]
name = "raiderbot"
version = "0.1.0"
description = "Discord guild management bot for character tracking and attendance"
requires-python = ">=3.11"
dependencies = [
    "asyncpg>=0.30.0",
    "discord-py>=2.6.4",
    "pytz>=2025.2",
]
